In [425]:
from selenium import webdriver
import time
import requests
from bs4 import BeautifulSoup
import pprint
import pandas as pd
import datetime

In [440]:
driver = webdriver.Firefox()
driver.get("https://resultadosemponto.com/")

In [427]:
# openTable = driver.find_element_by_xpath("//h2[@class='entry-title']")
# openTable.click()

In [441]:
url = driver.current_url
r = requests.get(url)
soup = BeautifulSoup(r.content, 'html.parser')
titles = soup.find_all('h2', {'class':'entry-title'})
articles = soup.find_all('article')

In [443]:
date = articles[0].find_all('h2', {'class':'entry-title'})[0].text.split()[-1]
hour = articles[0].find_all('h2', {'class':'entry-title'})[0].text.split()[-3]

In [518]:
soup.find_all('tbody')

[<tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">0100</td>
 <td class="text-center" nowrap="nowrap">25</td>
 <td class="text-center" nowrap="nowrap">Vaca</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">7923</td>
 <td class="text-center" nowrap="nowrap">06</td>
 <td class="text-center" nowrap="nowrap">Cabra</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">6739</td>
 <td class="text-center" nowrap="nowrap">10</td>
 <td class="text-center" nowrap="nowrap">Coelho</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">5493</td>
 <td class="text-center" nowrap="nowrap">24</td>
 <td class="text-center" nowrap="nowrap">Veado</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">5999</td>
 <td class="text-center" nowrap="nowrap">25</td>
 <td class="text-center" nowrap="nowrap">Vaca</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">6254</td>
 <td class="text-center" nowrap="nowrap">14</td>
 <td class="text-center" nowrap="nowrap">Gato</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0792</td>
 <td class="text-center" nowrap="nowrap">23</td>
 <td class="text-center" nowrap="nowrap">Urso</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td width="10%">1º</td>
 <td width="30%">5807</td>
 <td align="left">02 – ÁGUIA</td>
 </tr>
 <tr>
 <td width="10%">2º</td>
 <td width="30%">9246</td>
 <td align="left">12 – ELEFANTE</td>
 </tr>
 <tr>
 <td width="10%">3º</td>
 <td width="30%">6194</td>
 <td align="left">24 – VEADO</td>
 </tr>
 <tr>
 <td width="10%">4º</td>
 <td width="30%">3223</td>
 <td align="left">06 – CABRA</td>
 </tr>
 <tr>
 <td width="10%">5º</td>
 <td width="30%">0604</td>
 <td align="left">01 – AVESTRUZ</td>
 </tr>
 <tr>
 <td width="10%">6º</td>
 <td width="30%">5074</td>
 <td align="left">19 – PAVãO</td>
 </tr>
 <tr>
 <td width="10%">7º</td>
 <td width="30%">691</td>
 <td align="left">23 – URSO</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">9690</td>
 <td class="text-center" nowrap="nowrap">23</td>
 <td class="text-center" nowrap="nowrap">Urso</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">3807</td>
 <td class="text-center" nowrap="nowrap">02</td>
 <td class="text-center" nowrap="nowrap">Águia</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">2560</td>
 <td class="text-center" nowrap="nowrap">15</td>
 <td class="text-center" nowrap="nowrap">Jacaré</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">5817</td>
 <td class="text-center" nowrap="nowrap">05</td>
 <td class="text-center" nowrap="nowrap">Cachorro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">4454</td>
 <td class="text-center" nowrap="nowrap">14</td>
 <td class="text-center" nowrap="nowrap">Gato</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">6328</td>
 <td class="text-center" nowrap="nowrap">07</td>
 <td class="text-center" nowrap="nowrap">Carneiro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0889</td>
 <td class="text-center" nowrap="nowrap">23</td>
 <td class="text-center" nowrap="nowrap">Urso</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <td width="10%">1º</td>
 <td width="30%">1936</td>
 <td align="left">09 – COBRA</td>
 </tr>
 <tr>
 <td width="10%">2º</td>
 <td width="30%">2758</td>
 <td align="left">15 – JACARé</td>
 </tr>
 <tr>
 <td width="10%">3º</td>
 <td width="30%">6920</td>
 <td align="left">05 – CACHORRO</td>
 </tr>
 <tr>
 <td width="10%">4º</td>
 <td width="30%">9751</td>
 <td align="left">13 – GALO</td>
 </tr>
 <tr>
 <td width="10%">5º</td>
 <td width="30%">4908</td>
 <td align="left">02 – ÁGUIA</td>
 </tr>
 <tr>
 <td width="10%">6º</td>
 <td width="30%">6273</td>
 <td align="left">19 – PAVãO</td>
 </tr>
 <tr>
 <td width="10%">7º</td>
 <td width="30%">159</td>
 <td align="left">15 – JACARé</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">8083</td>
 <td class="text-center" nowrap="nowrap">21</td>
 <td class="text-center" nowrap="nowrap">Touro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">1532</td>
 <td class="text-center" nowrap="nowrap">08</td>
 <td class="text-center" nowrap="nowrap">Camelo</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">0711</td>
 <td class="text-center" nowrap="nowrap">03</td>
 <td class="text-center" nowrap="nowrap">Burro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">5321</td>
 <td class="text-center" nowrap="nowrap">06</td>
 <td class="text-center" nowrap="nowrap">Cabra</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">3609</td>
 <td class="text-center" nowrap="nowrap">03</td>
 <td class="text-center" nowrap="nowrap">Burro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">9256</td>
 <td class="text-center" nowrap="nowrap">14</td>
 <td class="text-center" nowrap="nowrap">Gato</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0383</td>
 <td class="text-center" nowrap="nowrap">21</td>
 <td class="text-center" nowrap="nowrap">Touro</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">7807</td>
 <td class="text-center" nowrap="nowrap">02</td>
 <td class="text-center" nowrap="nowrap">Águia</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">0808</td>
 <td class="text-center" nowrap="nowrap">02</td>
 <td class="text-center" nowrap="nowrap">Águia</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">4798</td>
 <td class="text-center" nowrap="nowrap">25</td>
 <td class="text-center" nowrap="nowrap">Vaca</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">2873</td>
 <td class="text-center" nowrap="nowrap">19</td>
 <td class="text-center" nowrap="nowrap">Pavão</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">3744</td>
 <td class="text-center" nowrap="nowrap">11</td>
 <td class="text-center" nowrap="nowrap">Cavalo</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">0030</td>
 <td class="text-center" nowrap="nowrap">08</td>
 <td class="text-center" nowrap="nowrap">Camelo</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0308</td>
 <td class="text-center" nowrap="nowrap">02</td>
 <td class="text-center" nowrap="nowrap">Águia</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">4411</td>
 <td class="text-center" nowrap="nowrap">03</td>
 <td class="text-center" nowrap="nowrap">Burro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">8740</td>
 <td class="text-center" nowrap="nowrap">10</td>
 <td class="text-center" nowrap="nowrap">Coelho</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">1751</td>
 <td class="text-center" nowrap="nowrap">13</td>
 <td class="text-center" nowrap="nowrap">Galo</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">6843</td>
 <td class="text-center" nowrap="nowrap">11</td>
 <td class="text-center" nowrap="nowrap">Cavalo</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">8058</td>
 <td class="text-center" nowrap="nowrap">15</td>
 <td class="text-center" nowrap="nowrap">Jacaré</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">9803</td>
 <td class="text-center" nowrap="nowrap">01</td>
 <td class="text-center" nowrap="nowrap">Avestruz</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0552</td>
 <td class="text-center" nowrap="nowrap">13</td>
 <td class="text-center" nowrap="nowrap">Galo</td>
 </tr>
 </tbody>,
 <tbody>
 <tr>
 <th class="text-center col-sm-1">Prêmio</th>
 <th class="text-center">Resultado</th>
 <th class="text-center">Grupo</th>
 <th class="text-center"></th>
 </tr>
 </tbody>,
 <tbody class="lista" id="lista">
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">1°</td>
 <td class="text-center" nowrap="nowrap">1876</td>
 <td class="text-center" nowrap="nowrap">19</td>
 <td class="text-center" nowrap="nowrap">Pavão</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">2°</td>
 <td class="text-center" nowrap="nowrap">9538</td>
 <td class="text-center" nowrap="nowrap">10</td>
 <td class="text-center" nowrap="nowrap">Coelho</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">3°</td>
 <td class="text-center" nowrap="nowrap">1781</td>
 <td class="text-center" nowrap="nowrap">21</td>
 <td class="text-center" nowrap="nowrap">Touro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">4°</td>
 <td class="text-center" nowrap="nowrap">4686</td>
 <td class="text-center" nowrap="nowrap">22</td>
 <td class="text-center" nowrap="nowrap">Tigre</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">5°</td>
 <td class="text-center" nowrap="nowrap">2581</td>
 <td class="text-center" nowrap="nowrap">21</td>
 <td class="text-center" nowrap="nowrap">Touro</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">6°</td>
 <td class="text-center" nowrap="nowrap">0462</td>
 <td class="text-center" nowrap="nowrap">16</td>
 <td class="text-center" nowrap="nowrap">Leão</td>
 </tr>
 <tr>
 <td class="text-center col-sm-1" nowrap="nowrap">7°</td>
 <td class="text-center" nowrap="nowrap">0893</td>
 <td class="text-center" nowrap="nowrap">24</td>
 <td class="text-center" nowrap="nowrap">Veado</td>
 </tr>
 </tbody>]

In [615]:
tds

[<td width="10%">1º</td>,
 <td width="30%">5807</td>,
 <td align="left">02 – ÁGUIA</td>,
 <td width="10%">2º</td>,
 <td width="30%">9246</td>,
 <td align="left">12 – ELEFANTE</td>,
 <td width="10%">3º</td>,
 <td width="30%">6194</td>,
 <td align="left">24 – VEADO</td>,
 <td width="10%">4º</td>,
 <td width="30%">3223</td>,
 <td align="left">06 – CABRA</td>,
 <td width="10%">5º</td>,
 <td width="30%">0604</td>,
 <td align="left">01 – AVESTRUZ</td>,
 <td width="10%">6º</td>,
 <td width="30%">5074</td>,
 <td align="left">19 – PAVãO</td>,
 <td width="10%">7º</td>,
 <td width="30%">691</td>,
 <td align="left">23 – URSO</td>,
 <td class="text-left" colspan="3">Soma: <b>30839</b></td>]

In [616]:
def get_data(articles):
    dfs=[]
    
    for j in range(len(articles)):
        
        # METADATA
        name1 = articles[j].find_all('h2', {'class':'entry-title'})[0].text.split()[3]       
        date = articles[j].find_all('h2', {'class':'entry-title'})[0].text.split()[-1]
        hour = articles[j].find_all('h2', {'class':'entry-title'})[0].text.split()[-3]
        objDate = datetime.datetime.strptime( (date + " " + hour[:-2]), '%d/%m/%Y %H:%M' )        
        
        # DATA
        tds = articles[j].find_all('td')
        ns = ['1°','2°','3°','4°','5°','6°','7°']
        PREMIO = []
        RESULTADO = []
        GRUPO = []
        for i in range(len(tds)-3):
            n=i                       
            if len(tds) == 22:
                    PREMIO.append(str(tds[n].text))
                    RESULTADO.append(tds[n+1].text)
                    GRUPO.append(tds[n+2].text.split()[0])
            for key in ns:
                
                if key in tds[i]:
                    PREMIO.append(str(tds[n].text))
                    RESULTADO.append(int(tds[n+1].text))
                    GRUPO.append(int(tds[n+2].text))
                
            n+=3
        dfs.append(pd.DataFrame({
            "DATA": objDate,
            "NOME": name1,
            "PREMIO": PREMIO,
            "RESULTADO": RESULTADO,
            "GRUPO": GRUPO
        }))

    return dfs

In [617]:
dfs = get_data(articles)

In [618]:
dfs[2]

Empty DataFrame
Columns: [DATA, NOME, PREMIO, RESULTADO, GRUPO]
Index: []

In [433]:
articles[i].find_all('h2', {'class':'entry-title'})[0].text.split()[-1]

IndexError: list index out of range

In [228]:
articles[i].find_all('h2', {'class':'entry-title'})[0].text.split()[3]

'PT-Rio'

In [232]:
articles[i+3].find_all('h2', {'class':'entry-title'})[0].text.split()[-3]

'18:20hs'